slogan: "The secret of happiness is to see all the marvels of the world, and never to forget the drops of oil on the spoon."

show_heart: true

show_slogan: true

menu:
  - title: 文章
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: 分類
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: タグ
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: コード
    url: downloads/code
    intro: "All download codes here."
    icon: "fa fa-download"

links:
  - title: "Java Guide"
    url: https://www.yuque.com/itwanger/gykdzg
    intro: "svao"
    icon: "fa fa-book"
  - title: "stackoverflow"
    url: https://stackoverflow.com/
    intro: "Seraching for solution."
    icon: "fa fa-stack-overflow"
  - title: "Typing Jungle"
    url: https://www.edclub.com/sportal/
    intro: "休闲，提升打字熟练度和双手协调度的好去处。"
    icon: "fa fa-keyboard-o"
  - title: "My Github"
    url: https://github.com/uncleTacitus
    intro: "My Github account."
    icon: "fa fa-github-square"
  - title: "LeetCode"
    url: https://leetcode.cn/problemset/
    intro: "algorithmic ladder."
    icon: "fa fa-trophy"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: 
fancybox: true
favicon: sakura.png
duoshuo_shortname:


# Analytics (change to yours)
google_analytics:
  enable: true
  siteid: UA-70812759-1

# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR
